name: Deploy to Server

on:
    push:
        branches:
            - main

env:
    SERVER_HOST: 94.103.93.13
    SERVER_USER: root
    SERVER_PATH: /root/scrapper

jobs:
    deploy:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.15.0"

            # Setup key
            - run: set -eu
            - run: mkdir "$HOME/.ssh"
            - run: echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
            - run: chmod 600 "$HOME/.ssh/key"

            # Deploy
            - name: Deploy to server
              run: rsync --archive --compress -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
